services:
  server:
    image: novadityap/attendance-app-server-dev
    container_name: attendance-app-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./server:/app
      - /app/vendor      
      - /app/bootstrap/cache
    networks:
      - attendance-app-dev

  client:
    image: novadityap/attendance-app-client-dev
    container_name: attendance-app-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./client/.env.development
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/app
    networks:
      - attendance-app-dev

  postgres:
    container_name: attendance-app-postgres-dev
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - attendance-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_app_dev
    networks:
      - attendance-app-dev

volumes:
  attendance-postgres-data:
    name: attendance-postgres-data
networks:
  attendance-app-dev:
    name: attendance-app-dev
