services:
  server:
    image: novadityap/attendance-platform-server-test
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "php artisan migrate:fresh --seed --force && php artisan test"
    volumes:
      - ./server/.env:/app/.env
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - attendance-platform-test

  client:
    image: novadityap/attendance-platform-client-test
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run build
    depends_on:
      server:
        condition: service_completed_successfully
    volumes:
      - ./client/.env:/app/.env
    env_file:
      - ./client/.env
    networks:
      - attendance-platform-test

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - attendance-platform-test

networks:
  attendance-platform-test:
