services:
  server:
    image: novadityap/attendance-app-server-test
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "php artisan config:clear && php artisan storage:link && php artisan migrate:fresh --seed --force && php artisan test"
    volumes:
      - ./server/.env:/app/.env
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - attendance-app-test

  client:
    image: novadityap/attendance-app-client-test
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run build
    volumes:
      - ./client/.env:/app/.env
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - attendance-app-test

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: attendance_app_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - attendance-app-test

networks:
  attendance-app-test:
