services:
  server:
    image: novadityap/attendance-app-server-ci
    build:
      context: ./server
      dockerfile: Dockerfile.ci
    env_file:
      - ./server/.env.ci
    depends_on:
      - postgres
    command: php artisan test
    networks:
      - attendance-app-ci

  client:
    image: novadityap/attendance-app-client-ci
    build:
      context: ./client
      dockerfile: Dockerfile.ci
    env_file:
      - ./client/.env.ci
    command: npm run build
    networks:
      - attendance-app-ci

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: attendance_app_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - attendance-app-ci

networks:
  attendance-app-ci:
