services:
  server:
    image: novadityap/attendance-app-server-test
    build:
      context: ./server
      dockerfile: Dockerfile.test
    env_file:
      - ./server/.env.test
    depends_on:
      - postgres
    command: php artisan test
    networks:
      - attendance-app-test

  client:
    image: novadityap/attendance-app-client-test
    build:
      context: ./client
      dockerfile: Dockerfile.test
    env_file:
      - ./client/.env.test
    command: npm run build
    networks:
      - attendance-app-test

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: attendance_app_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - attendance-app-test

networks:
  attendance-app-test:
