services:
  server:
    image: novadityap/attendance-platform-server-dev
    container_name: attendance-platform-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    command: > 
      sh -c "
        php artisan migrate:fresh --seed --force &&
        php artisan serve --host=0.0.0.0
      "
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./server:/app
    networks:
      - attendance-platform-dev

  client:
    image: novadityap/attendance-platform-client-dev
    container_name: attendance-platform-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - ./client/.env.development
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/app
    networks:
      - attendance-platform-dev

  postgres:
    container_name: attendance-platform-postgres-dev
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - attendance-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_app_dev
    networks:
      - attendance-platform-dev

volumes:
  attendance-postgres-data:
    name: attendance-postgres-data
networks:
  attendance-platform-dev:
    name: attendance-platform-dev
